# Generated by Django 5.0.6 on 2024-06-06 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_image_upload', '0008_alter_image_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='profile',
        ),
    ]
